server:
  port: 8003

dubbo:
  application:
    ###########注册到注册中心的名称############
    name: product-service
  ###########采用协议和端口号################
  protocol:
    ###########采用dubbo协议####################
    name: dubbo
    ###########发布dubbo端口号为20883###########
    port: 20883
  registry:
    ###########注册中心地址#####################
    address: zookeeper://123.57.46.173:2181
  scan:
    ############接口实现类的扫包范围###################
    base-packages: com.kingdom.product.service.impl