server:
  port: 9001

dubbo:
  application:
    name: user-web

  registry:
    address: zookeeper://123.57.46.173:2181

  consumer:
    timeout: 10000
# Swagger
swagger:
  title: DevPlatform Api 文档
  description: DevPlatform Api Documentation
  version: 1.0.0
  termsOfServiceUrl: https://gitee.com
  contact:
    name: Huang JingChao
    url: https://github.com/Kevin1118
    email: huangjingchao@2019.163.com

user:
  path:
    domain: http://localhost:9001
    upload: e:/360Safe