server:
  port: 8001

dubbo:
  application:
    ###########注册到注册中心的名称############
    name: user-service
  ###########采用协议和端口号################
  protocol:
    ###########采用dubbo协议####################
    name: dubbo
    ###########发布dubbo端口号为20881###########
    port: 20881
  registry:
    ###########注册中心地址#####################
    address: zookeeper://123.57.46.173:2181
  scan:
    ############接口实现类的扫包范围###################
    base-packages: com.kingdom.user.service.impl

spring:
  redis:
    database: 12
    host: 123.57.46.173
    port: 6379
    password: kingdom